Use guava version 10.0.1.
Latest guava version (11.0.1) causes integration tests to launch following error:

java.lang.NoSuchMethodError: com.google.common.io.Files.deleteRecursively(Ljava/io/File;)V
        at org.ops4j.pax.exam.spi.DefaultExamSystem.clear(DefaultExamSystem.java:214)

This is avoided using 10.0.1 version.

Seems that pax.exam requires such method, but it's not available in newer guava releases.
So we'll have to wait for newer pax.exam release to upgrade guava.